name: nestjs-cloudrun-app

on:
  push:
    branches:
      - master
      - main

env:
  PROJET_ID: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
  GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
  REGION: europe-west6
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.CREDENTIALS }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: code checkout
        uses: actions/checkout@v2
      
      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.GOOGLE_PROJECT }}
          service_account_key: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: build and push docker image
        env:
          GOOGLE_PROJECT: ${{ env.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker europe-west6-docker.pkg.dev
          docker build -t europe-west6-docker.pkg.dev/gitactions-cloudrun-test/gitactions-cloudrun-test/gaction-n-cloudrun:latest .
          docker push europe-west6-docker.pkg.dev/gitactions-cloudrun-test/gitactions-cloudrun-test/gaction-n-cloudrun:latest